### PR TITLE
added readHeading function; added calibration function

### PR DESCRIPTION
**Pull request by ActionNerd**
This is my first PR ever.  So if you see anything strange, please let me know and I will investigate, fix, study, whatever you need.

### CODE REVIEW

**Comment by praneshkmr** [comment]
Have you tested this code on the device? is it giving the expected values?

**Comment by praneshkmr** [comment]
As I am not in a position to test this library properly, I am thinking of Adding you as a contributor for this library. Is that Ok with you @ActionNerd ?

**Comment by ActionNerd** [comment]
Yep, it's been tested and works awesome on my hardware (Raspberry Pi).  It gives exactly the right values (although I had to do a calibration -- I put the general concept in your wiki).  I think it's pretty straight-forward code , but what do you think?  

I can come on as a contributor.  I'm not very experienced, so I may have a lot of questions along the way.    And I don't have a lot of time (as I work a lot in a non software developing job).  But sure.  Sounds fun.

**Comment by praneshkmr** [comment]
Great work. If the code works properly then, I think, it wont be a problem.
I will merge your PR.  BTW, even I am not experienced. I started exploring
IoT domain 6 months back.As long as you contribute for this library, I will
be happy. Also people who may use this library in future will surely be
happy. Happy Contributing.

On Sat, Jan 10, 2015 at 12:38 PM, ActionNerd notifications@github.com
wrote:

> Yep, it's been tested and works awesome on my hardware (Raspberry Pi). It
> gives exactly the right values (although I had to do a calibration -- I put
> the general concept in your wiki). I think it's pretty straight-forward
> code , but what do you think?
> 
> I can come on as a contributor. I'm not very experienced, so I may have a
> lot of questions along the way. And I don't have a lot of time (as I work a
> lot in a non software developing job). But sure. Sounds fun.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/praneshkmr/node-lsm303/pull/3#issuecomment-69446544.

## 

Regards
Pranesh Kumar R

**Comment by praneshkmr** [comment]
This closes #1 #2

**Pull request merged**
